// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4iFvsrjRzIhLanbN7M8GvNB3MH_WNhKc',
    appId: '1:998430415900:web:b3a65354aaed926e7993d9',
    messagingSenderId: '998430415900',
    projectId: 'nuggetberg-7bbed',
    authDomain: 'nuggetberg-7bbed.firebaseapp.com',
    storageBucket: 'nuggetberg-7bbed.appspot.com',
    measurementId: 'G-HWDNFDHG99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YXrlkeEdPsh6uFnqNkjH89dgLne-RLs',
    appId: '1:998430415900:android:57584e626e347c807993d9',
    messagingSenderId: '998430415900',
    projectId: 'nuggetberg-7bbed',
    storageBucket: 'nuggetberg-7bbed.appspot.com',
  );
}
